### ISSUE TITLE
Problems finding ModuleDefinitions

### ISSUE THREAD

**Issue by Randoom97** [SynBioDex/SBOLExplorer#107]
I was having issues redownloading modules that I've uploaded to SynBioHub from SBOLCanvas. I was able to replicate it on dev.synbiohub.org by uploading this file [test.zip](https://github.com/SynBioDex/SBOLExplorer/files/6281800/test.zip) (zipped because github doesn't support xml). Going to the collection it's in and filtering for module definitions works, but a string based search like objectType=<http://sbols.org/v2#ModuleDefinition>&collection=<https://synbiohub.org/user/randoom97/ReplicateModuleError/ReplicateModuleError_collection/1>& doesn't work.

**Comment by cjmyers** [comment]
Should be fixed now, please test @Randoom97

**Comment by Randoom97** [comment]
It is working now.
