### ISSUE TITLE
Create a separate SBOLExplorer log file

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOLExplorer#23]
This should be viewable on the SBOLExplorer admin page

**Comment by michael13162** [comment]
Logging has been added, and the /info endpoint now returns the log.  This endpoint should be changed to /log and the admin page need to be updated.

**Comment by cjmyers** [comment]
Need to add a button on the SBOLExplorer page to show the log file.

**Comment by yu-eric** [comment]
See https://github.com/SynBioHub/synbiohub/tree/logFileDownload

**Comment by cjmyers** [comment]
Fixed in SynBioHub
