### ISSUE TITLE
Serious bug with distributed search

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOLExplorer#24]
When a synbiohub cannot be reached (like SBH Utah that is down right now), it crashes SBOLExplorer.  It appears you are missing a try/catch to error out properly in this instance.

**Comment by michael13162** [comment]
This should be fixed.  Needs testing.

**Comment by cjmyers** [comment]
Also, dumps file appears to be missing even with distributed search off.

**Comment by cjmyers** [comment]
Running uclust
b'usearch v10.0.240_i86linux32, 4.0Gb RAM (16.4Gb total), 6 cores\n(C) Copyright 2013-17 Robert C. Edgar, all rights reserved.\nhttp://drive5.com/usearch\n\nLicense: michael13162@gmail.com\n\n'
Running uclust complete
parts: 0
hits: 0
Returning error float division by zero
Successfully updated config
Successfully updated config
Query for sequences
endpoint: http://virtuoso:8890/sparql?
Successfully updated config
00:01 101Mb   100.0% Reading usearch/sequences.fsa
00:01 119Mb   100.0% DF                           
00:01 120Mb  48557 seqs, 45124 uniques, 42942 singletons (95.2%)
00:01 120Mb  Min size 1, median 1, max 50, avg 1.08
00:01 121Mb   100.0% DB
00:01 122Mb  Sort length... done.
10000 20000 30000 40000 48557 
Query for sequences complete
Running uclust
Successfully updated config
Returning error [Errno 2] No such file or directory: 'dumps/uri2rank_dump'
Returning error [Errno 2] No such file or directory: 'dumps/uri2rank_dump'
Successfully updated config
Query for sequences
endpoint: http://virtuoso:8890/sparql?
Successfully updated config
03:53 237Mb    35.1% 15807 clusters, max size 10, avg 1.1

usearch/usearch10.0.240_i86linux32 -cluster_fast usearch/sequences.fsa -id 0.8 -sort length -uc usearch/uclust_results.uc

---Fatal error---
Empty file usearch/sequences.fsa

**Comment by yu-eric** [comment]
When purposefully misspelling the WOR URI, SBOLExplorer catches the error:

[2020-01-27 22:54:58.985679] [ERROR] Web of Registries had a problem!
[2020-01-27 22:54:59.115991] Successfully sparql searched

Looks like this has been fixed @cjmyers.

**Comment by yu-eric** [comment]
Should be fixed. See https://github.com/SynBioDex/SBOLExplorer/issues/27#issuecomment-579093008.

**Comment by cjmyers** [comment]
Ok, closing
