### ISSUE TITLE
Distributed search not robust to Web-of-Registries going down

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOLExplorer#27]
When WOR goes down, distributed search fails and reverts to normal search:

Error: {
  "error": "HTTPSConnectionPool(host='wor.synbiohub.org', port=443): Max retries exceeded with url: /instances/ (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:847)'),))"
}
 -> retrying query with SBOLExplorer bypassed
Error: {
  "error": "HTTPSConnectionPool(host='wor.synbiohub.org', port=443): Max retries exceeded with url: /instances/ (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:847)'),))"
}
 -> retrying query with SBOLExplorer bypassed

However, it could revert to non-distributed search.  Indeed, turning off distributed search gets it working again.

**Comment by yu-eric** [comment]
When purposefully misspelling the WOR URI, SBOLExplorer catches the error:

[2020-01-27 22:54:58.985679] [ERROR] Web of Registries had a problem!
[2020-01-27 22:54:59.115991] Successfully sparql searched

Looks like this has been fixed @cjmyers.

**Comment by cjmyers** [comment]
Sounds good
