### ISSUE TITLE
Should be able to set the default graph URI to empty string

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOLExplorer#35]
The SBH admin page does not allow you to set this field to an empty string.  Furthermore, setting this field, causes the query to not pickup public parts due to this code:

def send_query(query, endpoint):
    params = {'query': query}

    if endpoint == utils.get_config()['sparql_endpoint']:
        params['default-graph-uri'] = utils.get_config()['synbiohub_public_graph']

Should also reconsider why we are setting the default-graph-uri, since the security concern of exposing private parts should be handled elsewhere now.

**Comment by cjmyers** [comment]
Check if we still need the option synbiohub_public_graph

**Comment by cjmyers** [comment]
In explorer.py, get the default_graph_uri from the arguments of the "/" endpoint request.

In search.py, if _from is empty, use the default_graph_uri instead of synbiohub_public_graph

To check that this works, perform a search logged out with synbiohub_public_graph set to empty.

**Comment by yu-eric** [comment]
@cjmyers See #59
