### ISSUE TITLE
Add types and roles to data in the inverted index

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOLExplorer#4]
Add the types and roles to the inverted index and consider them during search when they are provided in the query.

**Comment by cjmyers** [comment]
Types in Table 2:

https://sbolstandard.org/wp-content/uploads/2016/06/SBOL2.3.0.pdf

Roles are defined in this OBO file:

https://github.com/The-Sequence-Ontology/SO-Ontologies/blob/master/Ontology_Files/so-simple.obo

**Comment by yu-eric** [comment]
Added in #68 .
