### ISSUE TITLE
Included usearch differ in version

### ISSUE THREAD

**Issue by yu-eric** [SynBioDex/SBOLExplorer#47]
The usearch for linux is on version 10.x, while the MacOS version is on 11.x. Will this cause any sort of compatibility issues?

**Comment by cjmyers** [comment]
Good question.  I've been using 11.x on MacOS fine, and we are using Linux version fine too.  So, I think this may be ok.
@michael13162 ?

**Comment by michael13162** [comment]
What Chris said^
