### ISSUE TITLE
Switch from USearch to VSearch

### ISSUE THREAD

**Issue by yu-eric** [SynBioDex/SBOLExplorer#48]
I discovered that there is an alternative to USearch, which has been aptly named [VSearch](https://github.com/torognes/vsearch). In short, it is developed on top of USearch, but has many more useful features, the most important being that it offers an open source 64-bit license, and is claiming to be more accurate than USearch. Many of the search commands are the same too. The only potential issue is that it does not support amino acid sequences or local alignments. Thoughts on switching to Vsearch? @cjmyers @michael13162

**Comment by cjmyers** [comment]
Sounds promising.  If it is not too difficult to support both, then having the ability to switch between them may make comparison easier, or if we later want to do amino acid sequences or local alignments, we could switch back.  How is the documentation?

**Comment by michael13162** [comment]
Agree with Chris^

SIMD sounds like it'd be faster, but it usually comes with architecture compatibility constraints.  I'm not sure what hardware we're running SBOLExplorer on these days.  

"VSEARCH uses an optimal global aligner (full dynamic programming Needleman-Wunsch), in contrast to USEARCH which by default uses a heuristic seed and extend aligner."
Supporting both sounds good.  Given this from their docs, it sounds like we'd need to validate performance.

**Comment by yu-eric** [comment]
Sounds good. We could implement some sort of switch for whether the user wants to use USearch or VSearch on the Admin page. For now, i'll get USearch working first.

**Comment by yu-eric** [comment]
VSearch has been tested and works as a direct drop-in replacement for USearch. I will add a radio that lets the user select between the two.

**Comment by yu-eric** [comment]
One advantage of using VSearch is that it also supports Windows, which USearch does not.

**Comment by cjmyers** [comment]
Sounds good

**Comment by yu-eric** [comment]
Final commit fixes radio, now user can switch between the two.
