### ISSUE TITLE
Error with SPARQL query to virtuoso

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOLExplorer#54]
[Error] Got status code when querying: 400
[2020-05-03 23:28:19.024286] Virtuoso 37000 Error SP030: SPARQL compiler, line 25: syntax error at ')' before '?subject'

SPARQL query:
define sql:big-data-const 0 
    PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
    PREFIX dcterms: <http://purl.org/dc/terms/>
    PREFIX dc: <http://purl.org/dc/elements/1.1/>
    PREFIX sbh: <http://wiki.synbiohub.org/wiki/Terms/synbiohub#>
    PREFIX synbiohub: <http://synbiohub.org#>
    PREFIX igem: <http://wiki.synbiohub.org/wiki/Terms/igem#>
    PREFIX prov: <http://www.w3.org/ns/prov#>
    PREFIX sbol2: <http://sbols.org/v2#>
    PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
    PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
    PREFIX purl: <http://purl.obolibrary.org/obo/>
    PREFIX ncbi: <http://www.ncbi.nlm.nih.gov#>
    
    SELECT DISTINCT
        ?subject
        ?displayId
        ?version
        ?name
        ?description
        ?type
        ?graph
    FROM <https://synbiohub.org/public> 
    WHERE {
    FILTER ()
        ?subject a ?type .
        ?subject sbh:topLevel ?subject .
        GRAPH ?graph { ?subject ?a ?t } .
        OPTIONAL { ?subject sbol2:displayId ?displayId . }
        OPTIONAL { ?subject sbol2:version ?version . }
        OPTIONAL { ?subject dcterms:title ?name . }
        OPTIONAL { ?subject dcterms:description ?description . }
    } 
    OFFSET 0 LIMIT 10000
[2020-05-03 23:28:19.024379] [ERROR] failed querying:http://virtuoso:8890/sparql?

**Comment by cjmyers** [comment]
Problem is with this line: FILTER ()

**Comment by yu-eric** [comment]
Should be fixed in latest commit.
