### ISSUE TITLE
Add to SynBioHub admin the ability to set the update interval

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOLExplorer#6]
This should update the cron job that runs the clustering, page rank, and index

**Comment by cjmyers** [comment]
We need to also determine if there is a cron job and where is it.

**Comment by yu-eric** [comment]
I found an alternative to using a local cron file here: https://www.npmjs.com/package/cron. What we could do instead is save a string var to SynBioHub's config file specifying the date formate to execute a cronjob (in the format of * * * * *), and pass that into a function that uses cron and runs the update index accordingly. @cjmyers

**Comment by cjmyers** [comment]
This sounds good to me.

**Comment by cjmyers** [comment]
Configuration file should include whether cron job is enabled and the timing of the job.  Default could be on with 24 hour update.  SBH should be able to change this configuration and start/stop cron job with new timing interval.

**Comment by yu-eric** [comment]
Added in #70 .
