### ISSUE TITLE
Make Full Sequence Search JSON Available via API

### ISSUE THREAD

**Issue by JMante1** [SynBioDex/SBOLExplorer#61]
It would be useful if the full sequence search were available via API, i.e. if not just the list of parts was returned but what the percentage match was between the search and the part, the length of the match etc

**Comment by cjmyers** [comment]
Should also return strand (+/-) and CIGAR for the position of the match

**Comment by yu-eric** [comment]
Link for CIGAR guide: https://jef.works/blog/2017/03/28/CIGAR-strings-for-dummies/

**Comment by yu-eric** [comment]
Sequence search data has now been added to the JSON being returned from SBH.
