### ISSUE TITLE
When no SBOLExplorer, change message to indicate that nothing is wrong

### ISSUE THREAD

**Issue by michael13162** [SynBioDex/SBOLExplorer#8]

**Comment by cjmyers** [comment]
Only show the error message when using SBOLExplorer is checked.

**Comment by yu-eric** [comment]
See https://github.com/SynBioHub/synbiohub/tree/explorerOffPage

**Comment by yu-eric** [comment]
Message has been added to the SynBioHub admin page when SBOLExplorer is off.
